# Generated by Django 6.0.4 on 2026-04-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [

        # Remove old field
        migrations.RemoveField(
            model_name='meal',
            name='position',
        ),

        # Add meal_type (Breakfast/Lunch/Dinner)
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('Breakfast', 'Breakfast'),
                    ('Lunch', 'Lunch'),
                    ('Dinner', 'Dinner'),
                ],
                default='Breakfast'
            ),
        ),

        # Fix day field
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.CharField(max_length=20),
        ),

        # ✅ FIXED ForeignKey (IMPORTANT)
        migrations.AlterField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(
                default=1,   # ✅ FIX: must be integer ID
                on_delete=django.db.models.deletion.CASCADE,
                to='recipes.mealplan'
            ),
            preserve_default=False,
        ),
    ]