# Generated by Django 6.0.4 on 2026-04-28 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_meal_options_alter_meal_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Comma separated ingredients', null=True),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('price_per_unit', models.FloatField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_items', to='recipes.recipe')),
            ],
        ),
    ]
