# Generated by Django 5.2.7 on 2026-04-30 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_groceryitem_unit_alter_groceryitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='recipes.recipe'),
        ),
    ]
