# Generated by Django 6.0.4 on 2026-05-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_meal_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='price_per_unit',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='category',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
